timezone: Asia/Shanghai
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
kramdown:
  input: GFM # GitHub Flavored Markdown
permalink: /:title/
url: haiiiiiyun.github.io
name: 蒋海云个人博客,日拱一卒。
title: 蒋海云个人博客,日拱一卒。
author: Haiiiiiyun
email: jiang.haiyun#gmail.com
twitter: haiiiiiyun
qq: 156227494
isso_comments: haiiiiiyun
beian: 
cnzz:
ga: UA-77551377-1 #Google Analytics
weibo:
github: haiiiiiyun
highlighter: rouge
safe: true
paginate: 20
about: "这里是蒋海云的个人博客。"
repository: haiiiiiyun/haiiiiiyun.github.io
plugins:
- jekyll-paginate
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
